### ISSUE TITLE
Add Codecov?

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/SpectroscoPyx#64]

**Comment by StanczakDominik** [comment]
Yes.

I've got my laptop set up decently now and I understand more about how to roll with the astropy template stuff now, so I should be able to do the whole setup thing this week.

Still thinking there's way less overhead to have this as plasmapy.spectroscopy.

**Comment by lemmatum** [comment]
Cool - I'd be happy to learn some more astropy templating stuff if you can suggest some links for me to lookup or discuss on matrix chat?

Yea the overhead is a pain, but I think it's better than overextending the mission of the plasmapy project. Also prevents dilution of the code base - keeping it relatively small and tidy.
That being said, if you feel overextended and don't want to spend time maintaining/developing for SpectroscoPyx then let me know.

**Comment by StanczakDominik** [comment]
Nah, don't worry. I'll get it done and besides this is an area of
contribution to SCIENCE that I'd be dumb to miss out on :D I'm just voicing
some doubts I've had about this issue to see where you stand  on it. I'll
get this done sometime this week.

**Comment by lemmatum** [comment]
Fair enough. I'm honestly hoping all this overhead/maintenance will become easier once we have the basic workflow setup, and that it'll just sort of run in the background with only occasional tinkering.

![image](https://user-images.githubusercontent.com/28945309/41004170-29742c76-68d6-11e8-93c0-e2d0e197afd7.png)

**Comment by lemmatum** [comment]
Closed by #63
