### ISSUE TITLE
Update documentation page from re-templating

### ISSUE THREAD

**Issue by lemmatum** [PlasmaPy/SpectroscoPyx#70]
The website still uses the astropy template for documentation whereas the documentation compiled by Giles uses a template consistent with PlamaPy. The website should be using the latter.

**Comment by StanczakDominik** [comment]
[Got it, it's better now](http://docs.spectroscopyx.org/en/latest/) :)

**Comment by lemmatum** [comment]
@StanczakDominik Sweet! Thanks for doing this!
